// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _, candiateWords, fs, path, removePunctuation, stopwords, stopWordsIso;
  path = require('path');
  fs = require('fs');
  _ = require('lodash');
  stopWordsIso = require('stopwords-iso');
  module.exports = stopwords = function (content, language) {
    var count, overlappingStopwords, stopWords, strippedInput, words;
    if (null == language)
      language = 'en';
    stopWords = stopWordsIso[language] || stopWordsIso.en;
    strippedInput = removePunctuation(content);
    words = candiateWords(strippedInput);
    overlappingStopwords = [];
    count = 0;
    _.each(words, function (w) {
      count += 1;
      if (stopWords.indexOf(w.toLowerCase()) > -1)
        return overlappingStopwords.push(w.toLowerCase());
    });
    return {
      wordCount: count,
      stopwordCount: overlappingStopwords.length,
      stopWords: overlappingStopwords
    };
  };
  removePunctuation = function (content) {
    return content.replace(/[\|\@\<\>\[\]\"\'\.,-\/#\?!$%\^&\*\+;:{}=\-_`~()]/g, '');
  };
  candiateWords = function (strippedInput) {
    return strippedInput.split(' ');
  };
}.call(this);
